### ISSUE TITLE
Void Slip causes health bars to disappear

### ISSUE THREAD

**Issue by ChimpyEvans** [Immemor/RaidCore#127]
If a spellslinger uses the void slip skill during an encounter, the health bars that are visible are removed from the window.

It's an annoyance, but there's no real issue other than the bars' disappearance. New health bars that are added don't cause issues, just ones that existed before void slip is cast.

**Comment by adamjedlicka** [comment]
Do you mean nameplates (healthbars over players and enemies). If yes then it's normal behaviour. You can't see nameplates when you don't see units which are associated to these nameplates. Same for blind.

**Comment by Immemor** [comment]
@adamjedlicka , you work on all projects. ^^

@ChimpyEvans Chimpy, if you post on this site, that means you speak about RaidCore health bar ? when did u meet this trouble ? on all void slip skill casted ? on specific encounter ? did you use the last release of RaidCore or the last alpha version ?

**Comment by adamjedlicka** [comment]
@Immemor sorry I thought its on ForgeUI. Nevermind :D

**Comment by ChimpyEvans** [comment]
I apologize for the delay in getting back to you guys!

It's the RaidCore health bars, the ones generated by AddUnit or WatchUnit.
I first noticed this on System Daemons, mainly because tracking their healths is important. When I cast Void Slip, however, both bars would always disappear and not come back after I exited void slip.

I just did a quick little runthrough of the core, block, and bars hierarchy and couldn't find any obvious reason. I suspect that the unit simply doesn't exist in the Void and the bar believes that the unit has been destroyed.

If you'd like to reproduce the issue, add any unit that doesn't exist in the void to the bars and, while the periodic updates are running, cast void slip to see that the bars just disappear.

**Comment by Immemor** [comment]
Ok, you very well describe the problem, you have totally right.

It's the same with:
- A player teleported on Avatus, when this last come back, he have no more features related to Avatus and/or Avatus's hands (lines and health bars).
- Kuralak who disappear at the beginning of the fight.

I started to fix it since few days ago at the root of RaidCore. I will try to finish on this days.
I'm a little slow, because I have big program to write for my possible new company, where I try to be hire.
