### ISSUE TITLE
Translation of the modules

### ISSUE THREAD

**Issue by olbat** [Immemor/RaidCore#15]
Hi,
I've made a small -dirty- script to translate RaidCore in French for our guild (it also have a German support).

You can find the script here: https://github.com/olbat/ws-raidcore-translator .

The main idea: it parses the source code of every RaidCore modules to find English strings and use the http://wildstar.datminer.com/ website to translate them.

It's working well for NPC and spell names, but not for zones names and messages (I suppose it need to be done by hand since no online db reference them).

The script can rewrite the modules in order to make them work in French/German (see https://github.com/olbat/RaidCore/tree/french and https://github.com/olbat/RaidCore/tree/german).

It can also generate JSON dumps of every translations with the format "English string" => "Translated string" (see https://github.com/olbat/ws-raidcore-translator/tree/master/dumps).

I was thinking this dumps may help you to create your language files ...

Please let me know if I can help you in any way :)

**Comment by NielsH** [comment]
Hey man,

This looks really cool, love the detailed readme :+1: 

I'll check this out a bit further in the weekend, I know there's some demand for translations atm, though I currently want to focus on adding the UI and boss-options. Translations up-next!

It'll be really cool in the end with lots of configurable options and multi client language support! :D

**Comment by olbat** [comment]
That would be great !

Do not hesitate to ask if you don't understand something or need some modifications (e.g. it would be possible, in some way, to get Spells/NPC/... id#)

**Comment by olbat** [comment]
Hi again :)

Just for you to know, I've modified my script in order to take in account the internationalization changes of the _translation2_ branch (#1).

Here is the diff of the French translated version of the addon: https://github.com/olbat/RaidCore/commit/d5cc43ff121a85aaa6d4597ecfd05ce08438315d .

The translations that can't be done by the script can be specified in a JSON file, there is a start of French translation file available here: https://github.com/olbat/ws-raidcore-translator/blob/master/french.json .

**Comment by NielsH** [comment]
Awesome, looking good :+1: 

Just as an FYI - currently I'm focussing on the UI stuff, so multi client support is kinda on the side. After UI stuff is done translation are a next step... Just so you're aware and don't feel like nothing is being done with this :-)

In the meantime, are there perhaps any french people people around that can translate the strings the converter doesn't pick up / the custom messages?

**Comment by olbat** [comment]
No problem, the script will still be working (I hope so) when you'll be done with your UI modifications so take your time ! :)

I think that I can find people to help me to with the translations (I'm not running the game in French), I'll keep you posted ...

One other thing, it would be wonderful if there were a way to make the difference between custom UI messages and messages used by the addon (boss dialog, ...) in the translation array.

It seems that one is really necessary for the add-on to work properly (exact translations needed) and the other is more cosmetic (custom translations ok), so if there were a way to make a difference between them, we would be able to focus our translation effort on the right Strings.

**Comment by NielsH** [comment]
There's a few ways we can do this.

Easiest way would be for me to prefix stuff... e.g. msgStrings["enUS"][warningPillar"] = "Pillar spawned, jump on it!" -> msgStrings["enUS"]["msg_warningPillar"] = "Pillar spawned, jump on it!"

Then we can reserve the msg_ prefix for custom strings that your script can watch for.

Alternatively we can do a seperate table.. msgStrings["enUS"]["custom"]["warningPillar"] = "Pillar sp..." - though that's a bit more effort for me :p 

Let me know!

**Comment by olbat** [comment]
Just do it the easiest way for you :)
As long as the prefix is always written the same way it will be easy to parse it.
I just hope it's not a too big re-factoring work for you ...

**Comment by NielsH** [comment]
Cool, we'll do it like that than. Hopefully I'll be able to do it this
weekend. :)
To clarify, I'll do the msg_ prefix

**Comment by olbat** [comment]
Perfect, thank you very much for your time ! :)

**Comment by Immemor** [comment]
Hi,

First, I will introduce myself for Olbat. I'm the author of DruseraBossMods, and I started my addon more or less in same time as RaidCore. At this moment, as I wasn't aware about RaidCore. And now, I decided to provide my time to RaidCore instead of provide another boss mod encounter.

So, As I already did the language support on my addon, I would like to propose you something identical and different in same time.

https://github.com/NielsH/RaidCore/compare/master...Immemor:translation_proposal
I did only X-89 as example.

I have an important feedback for you. 
- In french, there are some 'no break space' hidden in Messages or boss name (like System Daemon), so the direct translation like you did will not work.

At programing level:
- I prefer to use GeminiLocale library, because this last already manage missing translation.
- In my method, The current language is save in GeminiLocal, others are dropped. I save some memory like that.

I'm currently looking the RegisterZone, RestrictEvent... For zone, i don't understand why you use a string to identify the Room. The ZoneId  and ZoneParentId from GetCurrentZoneMap API should be perfect for that.  And number don't need to be translated. ^^
But, I haven't finish to read all. I still analyzing.

**Comment by Immemor** [comment]
Additional Info:
- For french translation, we can take them from DruseraBossMods, when they are available. It's an another source.
- In the my proposal branch, I added a regular expression for the datachron message of X-89. It's better, than what I seen.
- Another advantage of GeminiLocale is the translation for windows.
- In my implementation, you don't need to translate all boss in same time. That can be done step after step, on few weeks.

**Comment by Immemor** [comment]
NielsH,

Can I create another issue to replace your RestrictedZone,EnableZone ?

Instead of string to identify the zone, I would like to use numeric Identifiers with: 
- GameLib.GetCurrentZoneMap().continentZoneId 
- GameLib.GetCurrentZoneMap().parentZoneId 
- GameLib.GetCurrentZoneMap().Id
- GameLib.GetCurrentZoneId()

For  parentZoneId and Id, I have already the values in DruseraBossMod.

**Comment by NielsH** [comment]
Hey @Immemor  - I'm glad you're willing to help out!

Zonewise we initially only had English, there's no specific reasoning behind using the name over the id - name was simply easier to read. However since we are slowly getting multi-client support now it'd probably be better to switch to ids

I've had a quick look at your proposol, I do have a few questions:
- What are you using RC_UnitCreated & RC_UnitDestroyed for? I can see it being fired in unitCheck, but I don't see any handlers for it. unitCheck is the current event handler for UnitCreated.
- Why use RC_UnitStateChanged over the current UnitStateChanged?
- Why remove https://github.com/NielsH/RaidCore/compare/master...Immemor:translation_proposal#diff-fb34fdb831a0474a150632a4f8498208L508 , since we use it 2 lines below that :)

The script made by @olbat does need some kind of indication so we can differentiate between exact matches (cast names, datachron messages, chat messages, mob names) and informational messages we add ourselfs. With the current mod:Register*Locale we will also need to add this msg_ prefix, or we need another way of doing this. Is that fine with you?

Heads up if you're planning on changing the Enable/RestrictedZone to use ids, we will still need support for multiple zone ids, for the Elemental Pairs for example.

Looking forward to your response! :-)

**Comment by Immemor** [comment]
- We need to replace handler from carbine by a first level of interpretation. With the first level of interpretation, we can replace all 'no break space' by space. In the third commit (https://github.com/NielsH/RaidCore/commit/e669030ef816b595989a2c860c4a47f4884f465a#diff-66cc8ba51494ecbd20e7c5a96096196bL26), I replace the RegisterEventHandler  of "UnitEnteredCombat" by "RC_UnitStateChanged". If you have looked the second commit only, for sure it's not used, the second commit is a preparation commit for all boss modifications.
- The answer is to provide an unit name without "no break space".
- I'm not sure to have understood your question. Is it about the sName variable moved 2 lines before ?

About the indication for automatic translation, we can put a prefix or suffix in the keyword of each entry of the locale.
Example:
Instead of
  ["KNOCKBACK"] = "KNOCKBACK",
We can write
 ["MSG_KNOCKBACK"] = "KNOCKBACK",

Here I added 'MSG_' as prefix.
Is it answers to your question ? With a regular expression, that should be easy to translate all, by a tool.

I started this idea to change zone identification with numeric identifier since 2 hours now. You have registered many Sub Zone, for one element pair.
Because currently, all is based on OnSubZoneChanged() function.
If you removed this limitation, and use all informations from GetCurrentZoneMap() also. That should be enough.
In fact, we have many value of subzone for 1 pair, but we have 1 ZoneMap for 1 pair.

**Comment by Immemor** [comment]
Otherwise, I glad that you accept me in your project too ^^

**Comment by NielsH** [comment]
Alright - if the RC_ event handlers replace the existing ones with the exception of the main one that applies the no break space that's fine :+1: 

Regarding the sName, I'm just blind, didn't see you moved it to above the if-block, reading is hard...

Besides that, sounds good! I think for now it'd be best to push a next version to Curse with options at least, after that we can add the translation stuff into the master and work from there with your improvements!

**Comment by Immemor** [comment]
Hum, I think there are some permissions to have., If I want to push in your git, but in master a branch, isn't it ?

Because I rebased my work on the current master, and when I try to push something, I have:

$ git push origin translate_proposal:translate_proposal_rebased
remote: Permission to NielsH/RaidCore.git denied to immemor.

I would like to process like that , to avoid merge operation, and because fast & forward is better.

**Comment by NielsH** [comment]
I've given you push access to the repository. If you plan on refactoring a lot of stuff please take into account that I do want to use the git version to ocassionally create Curse version, so we do need to be sure that the changes are properly tested and don't give errors in boss fights/during normal usage :+1:

**Comment by Immemor** [comment]
Don't worry, in my profession, every commits must compiled, provided with tests, and pass all tests of the system.
And every night, the system is tested, with reports provided in home web page.

Also, an review must be done by another guy before push in master. Where the reviewer check the coding style, and quickly look if he can detect an algorithm error.

As you are agree with the structure, I will provide you a branch in review where I did all translation which I can do. Give me the day, or 2 maybe. :)

**Comment by NielsH** [comment]
Awesome - for my work I don't have to do a lot of programmming, just some small scripts sometimes to help make things easier, but I've always only done solo projects as a hobby thing, like RaidCore and earlier BetterRaidFrames and BetterPartyFrames :).

Cool to have someone helping out now and seeing the interest in RaidCore. Looking forward to it ^^

**Comment by Immemor** [comment]
Ohh, I can understand you on this point. I was alone on DruseraBossMods.. It's a little hard to finalize a project.
I glad to work with you too.

**Comment by olbat** [comment]
Hi there,
First of all, thanks for your details @Immemor, nice to meet you :)

Can you tell me if your work on using GeminiLocale (https://github.com/NielsH/RaidCore/compare/master...Immemor:translation_proposal) is still in progress ?

If it can help, I can try to modify a little my script in order to rewrite modules for you (I think it will not be perfect/working but it may make you win some time ...): add self.L[...] calls + mod:RegisterLanguageLocale() with values and translations when possible ?

If you want to work on modules boss by boss, I can use the script then do a commit (or branch) per boss, just let me know what you prefer :)

Just let me know if your improvements are in a stable version so I'll be able to adapt my -dirty- parser ...

**Comment by Immemor** [comment]
Yes, I have almost finished the first step. 

I pushed a wip branch.
https://github.com/NielsH/RaidCore/tree/wip/imme/translate

I hope to finish Elemental Pairs today. I tested Maelstrom Authority yesterday in English. It's seem I broken nothing.

**Comment by olbat** [comment]
Oh cool, I'll try to modify my script tomorrow :)

Did you manage to add those "MSG_" prefixes ?

**Comment by Immemor** [comment]
Ok, I rebased my work on master's HEAD. And so I updated my WIP branch

I don't manage prefix, as we haven't establish anything. I means no format.

**Comment by Immemor** [comment]
From what I see on github, you don't use "git rebase" command, to avoid merge.

https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase

**Comment by Immemor** [comment]
I you have comments to do any commit, don't hesitate. I better to fix before push in master.

**Comment by NielsH** [comment]
I noticed that some translation strings are missing in the French version. Is that something that GeminiLocales automatically picks up and falls back to the English one? Or should it be included?

For example, Gloomclaw https://github.com/NielsH/RaidCore/blob/wip/imme/translate/Modules/Gloomclaw.lua is missing `Essence of Logic`, `BURN HIM HARD`, and `Corrupting Rays` in the french locale

**Comment by Immemor** [comment]
When the translation is missing,  GeminiLocale will:
- Print a warning with the line and file, and also the namespace.
- And falls back to the entry name.

It's maybe possible to force GeminiLocal to used the english, with a force option during the registering.
But I think it's useless when you have a french or german client.

At least, no lua error are raised like that.

**Comment by olbat** [comment]
Erm in fact, it's just that some work has been made on master since I made my last run :)

Btw it's possible to run the script on the code at any time, I'll do one run it after my modifications.

Is there some boss modules you did not convert (to use GeminiLocale) yet ?

If not i'll try to find missing translations only (no convertion of self.L[]+mod:RegisterLanguageLocale() elements).

**Comment by Immemor** [comment]
Few Elemental pair aren't converted, I'm closed to finish.

**Comment by Immemor** [comment]
Also, I haven't converted buff name for SD and Avatus. I opened a ticket for that.

**Comment by Immemor** [comment]
If one of you , use VIM as editor.

I did this rule, to highlight the translation code:

```
syntax match Locale '\<self.L\["[a-zA-Z1-9\ \-\.\[\]%!&#{}~:]*"\]'
highlight default link Locale Macro
```

**Comment by Immemor** [comment]
Ok , I pushed a version with all boss modified, in review (https://github.com/NielsH/RaidCore/tree/review/translation).

Before my rebase on master, I killed Maelstrom with my changes, and all works.
Tonight (after the rebase on master), I killed Gloomclaw, but RaidCore seems to not recognize the boss.
I will review myself too, during this few days, to understand.
But RaidCore have a lack of debug tool. I'm think, I will import my trace system, which I have built on DruseraBossMods.

Otherwise, translation job could really start now.
I will look how to adapt Zone "access"... tomorrow with a wiki page about rebase command on git. 

EDIT: When I will push in master, I will clean my wip and review branch of course.

**Comment by olbat** [comment]
Ok, I modified the script and made a run on the _review/translation_ branch, here is the diff: https://github.com/NielsH/RaidCore/compare/review/translation...olbat:i18n_v2 .

The script rewrites the code and add _RegisterLanguageLocale_ blocks with translations for each given name.

If no translation is available, it keeps the english version and add a "-- !!!!" comment at the end of the line (so this lines can be "grepped" easilly).

For the moment it comments existing _RegisterLanguageLocale_ blocks, the merge of existing translations <-> generated trranslations have to be done by hand, if I have the time I'll see if I can do it automatically.

An example of code replacement with the Experiment X-89 module: 
- The existing translation block is commented: https://github.com/NielsH/RaidCore/compare/review/translation...olbat:i18n_v2#diff-66cc8ba51494ecbd20e7c5a96096196bR96
- A new translation block is generated: https://github.com/NielsH/RaidCore/compare/review/translation...olbat:i18n_v2#diff-66cc8ba51494ecbd20e7c5a96096196bR53

Do not hesitate to ask if you need some explanations or modifications :)

**Comment by Immemor** [comment]
You don't need to keep the english version. The GeminiLocale already do it.

You should not set the entry if the translation is missing.

**Comment by Immemor** [comment]
on EpLifeLogic, your translation result is:

``` lua
["MARKER North"] = "MARKER North",
```

Be careful, the key is not really the sentence to translate. You should catch the entry value in the english part.

**Comment by olbat** [comment]
**Reminder**
If at any moment you want to run the translation script on some Raidcore code, just do:

```
$ docker pull olbat/ws-raidcore-translator
$ docker run -v /path/to/Raidcore:/src/ olbat/ws-raidcore-translator \
    raidcore-translator i18n_v2 -l fr -v /src/Modules
```

Or if you're not using [Docker](http://www.docker.com):
1. [Install](https://www.ruby-lang.org/en/documentation/installation/) ruby runtime environment
2. [Install](http://www.nokogiri.org/tutorials/installing_nokogiri.html) the Nokogiri library: `gem install nokogiri`
3. Run the script: `raidcore-translator i18n_v2 -l fr -v /path/to/Raidcore/Modules`

See the [README file](https://github.com/olbat/ws-raidcore-translator/blob/master/README.md) for more information.

**Comment by olbat** [comment]
My bad, I'll fix this bug ASAP :)

Ok for the fact of keeping the english version, I made it like this to track what translations are missing. I'll modify the script to add this lines as comment so we can still track what's still needed to be done :)

**Comment by Immemor** [comment]
hum, it's a good idea. In this comment, could you add the keyword "TODO", in upper case. Some editors will highlight it.

Otherwise it's a great job. I will look the zone registering, and trace system to debug faster.

**Comment by Immemor** [comment]
Is it you or the ruby script which put in comment the old registering french and german ?

to reduce the diff, you can erase them.

**Comment by olbat** [comment]
In fact I automatically add the block comment (--[[ + --]]) to existing French and German registering blocks in order to keep already existing translations for manual merging (since some bosses have already been translated ...) :)

**Comment by Immemor** [comment]
Ok, you can delete them so. If there are some differences, we will see it with the commit diff.

**Comment by olbat** [comment]
Modifications done (without deleting the comments, I'll do it ASAP): https://github.com/NielsH/RaidCore/compare/review/translation...olbat:i18n_v2-2 .

**Comment by olbat** [comment]
Here is the last version (with no the comments): https://github.com/NielsH/RaidCore/compare/review/translation...olbat:i18n_v2-3 .

You were right, logs are really easier to read + it's easy to find out what has been lost via `git show --stat` or something like this :)

**Comment by Immemor** [comment]
Beautiful ^^. It's great. It's easier to review :)

On Gloomclaw, I used a piece of the datachron message instead all the message itself as the key. So It's maybe why you haven't found the translation.

**Comment by olbat** [comment]
In fact, I'm using the http://wildstar.datminer.com/ website to translate Spells/NPC/Item/... names so most of time, there is no translations for Datachron/Chat messages :)

**Comment by olbat** [comment]
I made few modifications in order to be able to load existing translations from _review/translation_ and _translation2_ (see #1), here is the diff: https://github.com/NielsH/RaidCore/compare/review/translation...olbat:i18n_v2-4 .

Instructions to extract existing translations are available in the [README file](https://github.com/olbat/ws-raidcore-translator/blob/master/README.md) ([fr](https://github.com/olbat/ws-raidcore-translator/blob/master/README.md#read-existing-translations-and-translate-2),[de](https://github.com/olbat/ws-raidcore-translator/blob/master/README.md#read-existing-translations-1-and-translate-2)).

**Comment by olbat** [comment]
If you are curious, here is the diff between _i18n_v2-3_ and _i18n_v2-4_: https://github.com/olbat/RaidCore/commit/f38fcb8b1fb2a91bba0dab7e0bffd6ffedab246c .

**Comment by Immemor** [comment]
In the v2-4:
- The Ohma datachron messages have been translated in german, but not in french.  is it normal ?
- On Maelstrom, you translated NORTH by N, but in this boss, the full word is used.

When I have a moment, I should look how you built your tool. Did you stop the project Armory on github ?

**Comment by olbat** [comment]
**Ohmna**
To translate German, the script read existing translations from the _translation2_ branch ([doc](https://github.com/olbat/ws-raidcore-translator/blob/master/README.md#read-existing-translations-1-and-translate-2)).
Since there were some datacron translations for Ohmna [in this branch](https://github.com/NielsH/RaidCore/blob/translation2/Modules/Ohmna.lua#L85), the script was able to generate german translations.

To translate French, the script is using existing translations from the _review/translate_ branch ([doc](https://github.com/olbat/ws-raidcore-translator/blob/master/README.md#read-existing-translations-and-translate-2)).
Since there is not translations for datacron messages [in this branch](https://github.com/NielsH/RaidCore/blob/review/translation/Modules/Ohmna.lua#L47), no translations were generated.

That's why there is datacron translations for Ohmna in German but not in French.

**Maelstrom**
Concerning Maelstrom, I think that the translation of "NORTH" is coming from https://github.com/NielsH/RaidCore/blob/translation2/Modules/Ohmna.lua#L103 .

**Armory**
Erm the project is kinda "paused", we were planing to add support of runes, stats, ... but since the project/add-on did not have a lot of success, we stopped the developments for the moment :)

**Comment by Immemor** [comment]
If there is no more comment, I will push in master with autosquash option. In others words, commits which start with "fixup!" will be merge before push.

If you don't known autosquash option, I copied the help:

When the commit log message begins with "squash! …" (or "fixup! …"), and there is a commit whose title begins with the same …, automatically modify the todo list of rebase -i so that the commit marked for squashing comes right after the commit to be modified, and change the action of the moved commit from pick to squash (or fixup). Ignores subsequent "fixup! " or "squash! " after the first, in case you referred to an earlier fixup/squash with git commit --fixup/--squash.

**Comment by olbat** [comment]
Okay, nice :+1:
We'll be able to focus scripts output and the missing translations :)

I was just thinking: did @NielsH finish his work on the UI ? (from what I remember, he said that he wanted to finish his work on the UI before merging the work on translations)

**Comment by Immemor** [comment]
Well, As we don't merge. That have no importance.

master is a branch with feature which work. When you push in master, it's not mandatory to do a tag.
He can take his time to finish, in fact.

**Comment by NielsH** [comment]
Currently I just need to add the options in the code for the elemental
pairs. UI part is done! Well, mostly, need 2 more buttons... But will
finish that up in the weekend ;)

**Comment by Immemor** [comment]
Ok, there is no need to be synchronized together. It's 2 different features.

Otherwise, Everybody is agree to push the review/translation branch in master ?

**Comment by NielsH** [comment]
Yeah, definitely, go for it!

**Comment by olbat** [comment]
@Immemor sry, I thought that you were speaking about merging in master :) What do you mean by pushing in master ? Rebase + merge ff in master ?

I must have mis-understood something :)
I was thinking @NielsH wanted to make two releases: one with the UI, the other one with the translations (merging in master with the work on the UI still in progress, would have make it impossible) :)

If my opinion have any importance: I think that the work on _review/translation_ seems to be clean and ready :)

**Comment by NielsH** [comment]
That was originally what I wanted to do, but Immemor worked so quickly with all the translations it might as well just be added in now, since it worked well in the DS run we did this reset!

**Comment by Immemor** [comment]
it's pushed in master, you can rebase your branches.

I will continue on zone restrictions and trace system too.

**Comment by olbat** [comment]
Nice ! :)
I've made a pull request (#37) with French and German translations (from [web db](http://wildstar.datminer.com/) and _translation2_ branch).

I also added the langage name in the TODO comment lines in order for translators to be able to easilly find missing translations.

Translations used to convert the modules has been dumped in two JSON files ([fr](https://github.com/olbat/ws-raidcore-translator/blob/master/french-full.json),[de](https://github.com/olbat/ws-raidcore-translator/blob/master/german-full.json)), missing translations have the _null_ value.
If this files are amended by translators, it will be easy to update the modules.
