### ISSUE TITLE
Updates for Multilanguage-Support

### ISSUE THREAD

**Issue by Eikju** [Immemor/RaidCore#17]
Hey there :)

I saw a lot of boss updates but it is very frustrating to see that the updates are only available for the English client. My idea of the German translation and Multilanguage-Support was to get the new boss updates as well as the English guys and not so much work for "recopying" the new updates in my older files.

**Comment by NielsH** [comment]
They'll be merged in at some point into the master. When that happens the updates after that will be into the branch that has the german support into it.

For me the current focus is simply not multi language support. I don't have a lot of time to work on raidcore, and when I do, it's on other things I like to do more and which I think are more important.

I won't merge in changes into the master without knowing for certain they work well, since this will affect all users otherwise.

I've said it on Curse as well, it's very much beta software, and you should not expect a finished product at this point. In time all the cool features will be in, but for now please be patient ;)
